# Generated by Django 5.2.7 on 2025-11-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
