# Generated by Django 5.2.7 on 2025-11-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_avatar_alter_userprofile_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('ai_ml', 'AI / ML'), ('design', 'Design'), ('business', 'Business'), ('language', 'Language Learning'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
